### ISSUE TITLE
Proposal to use Github and single VSK_Map or single VSDK_Avatar source repositories

### ISSUE THREAD

**Issue by fire** [V-Sekai/V-Sekai.github.io#194]
Goal: Store source assets in version control and allow remixing in a social network. 

1. Make a separate personal organization
1. Single VSK_Map or Single VSK_avatar per git repo
1. Use github
2. git-lfs, DVC and git-annex are banned
3. Regular limits of github 
  * 100 MB single files
  * total repository size on Github is < 5 GB
 
### Special consideration

4. `git config --global alias.squash-all '!f(){ git reset $(git commit-tree HEAD^{tree} -m "${1:-A new start}");};f'` `git squash-all`

**Comment by lyuma** [comment]
.tres and .tscn files over 10MB should ideally not be committed. It might be a good rule to avoid committing .res, .scn or .tres or .tscn files with binary assets.

**Comment by fire** [comment]
Todo: Transfer into a proposal.

**Comment by fire** [comment]
I have created https://github.com/V-Sekai-fire/.
