### ISSUE TITLE
Restore locomotion options

### ISSUE THREAD

**Issue by lyuma** [V-Sekai/V-Sekai.github.io#216]
1. first step is determine if input is working. (including godot action system or openxr actions as appropraite)
2. Second is see if it's being funneled through the appropriate managers.
3. and finally see where it sets the position (e.g. XROrigin recenter?)

**Comment by fire** [comment]
- [ ] Teleport
- [ ] Smooth walking

**Comment by fire** [comment]
Status: Can't display the mesh imposter

**Comment by fire** [comment]
Stuck when going up ramp in uro://2036514f-3ecf-44bd-9d12-ff0dcbc98c07

**Comment by fire** [comment]
Vignette-ting on both turning and smooth walking. I tried and it was pretty good for making me comfortable.

I want to use that as the fallback safe for everyone mode.

The first example of the Vignette mode was done in Google Earth VR.

**Comment by fire** [comment]
We restored one locomotion method. Smooth locomotion. Will open new bugs for the other ones.
