### ISSUE TITLE
Demo video/World creation tooling

### ISSUE THREAD

**Issue by fire** [V-Sekai/V-Sekai.github.io#287]
### Request description

- [ ] vroid screenshot, and show that it came from .vroid to .vrm file
- [ ] Don't show downloading vsk project.
- [ ] Show blender screenshot of vrm, "Export from VRM compatible creation tooling" (picture of blender)
- [ ] Don't show UI of vroid studio, other than 
- [ ] Then, show vrm file importing to Godot with vsk tools
- [ ] change progress bar to spinner.
- [ ] Then, show our UI for upload. disable the progress bar.

**Comment by lyuma** [comment]
Did first recording. In google drive

**Comment by fire** [comment]
The deadline for the presentation has past. Will need to evaluate controller based only support for GDC 2023.
