### ISSUE TITLE
AnimationLibrary should use properties instead of dictionary for child animations.

### ISSUE THREAD

**Issue by lyuma** [V-Sekai/V-Sekai.github.io#340]
### V-Sekai version

*

### System information

*

### Issue description

We need to get a patch to godot before beta to make AnimationLibrary api more stable.

### Steps to reproduce

import AnimationLibrary and save tscn or tres. clips are stored in dictionary

**Comment by fire** [comment]
@lyuma Please make a bug report on Godot Engine org.
