### ISSUE TITLE
Migrate SkeletonModification3D runtime state to Node or RefCounted

### ISSUE THREAD

**Issue by lyuma** [V-Sekai/V-Sekai.github.io#341]
### V-Sekai version

*

### System information

*

### Issue description

SkeletonModification3D and SkeletonModificationStack3D are resources which make it awkward to hold runtime state. Also SkeletonModificationStack3D is an indirection via resource which makes it impossible to add additional modifications to an existing object 

### Steps to reproduce

Use skeleton modifications, then duplicate the node.

**Comment by lyuma** [comment]
see github comments. there were some leftovers from original version such as cache that still need to be removed.

**Comment by fire** [comment]
Lyuma is worked on the 3d IK Nodes and now is working on the 2D IK nodes.
