### ISSUE TITLE
Migrating animation and import_pipeline from humanoid_data to new retargeter

### ISSUE THREAD

**Issue by lyuma** [V-Sekai/V-Sekai.github.io#346]

**Comment by lyuma** [comment]
1. remove humanoid_data bone map.
2. make new bone map work
3.

**Comment by fire** [comment]
Completed as of https://github.com/V-Sekai/godot-vrm/commit/94c3d33adcbabe704d906c92e20eb664d4cc9b26 @lyuma can you close?

**Comment by fire** [comment]
Completed.
