### ISSUE TITLE
Implement documentation using readthedocs github actions

### ISSUE THREAD

**Issue by lyuma** [V-Sekai/V-Sekai.github.io#347]
- [ ] Use github actions for read the docs
- [ ] Use the exact infrastructure godot engine uses
- [x] Signup for readthedocs
- [ ] https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html
- [ ] Package into uro

**Comment by fire** [comment]
Apparently godot engine uses restructure text, and mkdown is down via mkdocs.

**Comment by fire** [comment]
Concerns from review of existing documentation website.

1. Search doesn't work.
2. Lose place in the website.

**Comment by fire** [comment]
After flailing, I wasn't able to use read the docs.

1. Added better search and choose a better designed theme for quarto that allows you click on the titles sections and not just the text.

**Comment by fire** [comment]
Photos of the new site.

![image](https://user-images.githubusercontent.com/32321/188100232-5ec16d3b-83a0-4a20-a47d-222fddeaade7.png)

![image](https://user-images.githubusercontent.com/32321/188100281-6b1b6871-d0b5-4261-bd3a-0ffd8a5bc7ae.png)

**Comment by fire** [comment]
The biggest dealbreaker was that godot docs uses restructured text and we use markdown.
